### PR TITLE
Fix null pointer exceptions on page import

### LINKED ISSUE #172: import segmentation without `@type`
When I open existing PAGE-XML files with standalone LAREX – yes, I have managed to get around #160 and #162 in a Docker build (so when I have time, we'll get to the bottom of this) – then the UI keeps showing an hourglass and I see these exceptions on the console:

```
	at org.primaresearch.dla.page.layout.physical.text.impl.TextRegion.getTextType(TextRegion.java:149)
	at de.uniwue.web.io.PageXMLReader.getPageAnnotations(PageXMLReader.java:99)
	at de.uniwue.web.io.PageXMLReader.loadPageAnnotationsFromDisc(PageXMLReader.java:208)
	at de.uniwue.web.controller.DataController.getAnnotations(DataController.java:94)
```

(This is with the prima-core-libs 1.4.02 repackaged in current master.)

The error goes away when I add `@type` annotations for the regions.

Again, this strikes me as overly restrictive.

### PR DESCRIPTION
**Pull request by bertsky**
Fixes #172 (and another, similar bug w.r.t. `TextLine/@index`)

### CODE REVIEW

**Comment by bertsky** [comment]
These patches have not been applied during the recent merges. Should I redirect the PR to master?

**Comment by bertsky** [comment]
@maxnth I updated the PR to the upstream changes. I wonder why you have not merged it yet, though.

Meanwhile, I have found another bug: if for some reason, a `TextRegion` without `@type` survived import, then the PageXMLWriter must be able to cope with it, too. (Also throws NPE currently.) Do you want me to add a fix for that as well?

**Comment by maxnth** [comment]
>@maxnth I updated the PR to the upstream changes. I wonder why you have not merged it yet, though.

I used your fix (thanks for that) in a feature branch that was supposed to contain all other changes which are needed to allow LAREX to work with text regions without a type (UI + PageXMLWriter) as you already mentioned.
Sadly some other things got in the way and I didn't yet come to actually implementing these.

If it helps, I could add this fix to `dev` directly, otherwise I'd add it when the branch is complete.

**Comment by bertsky** [comment]
I see. Well, there's no such feature branch on the server, and no messages here, and then there was a new conflicting change right in the same section which I had to merge, so I just assumed this got forgotten.

No, it's fine with me. I can keep up my own `master` as long as necessary. I'll probably wait merging your `dev` activity until you found time to deal with this.

**Comment by maxnth** [comment]
The proposed fix is now available in the dev branch (see #172).
If the implemented behavior doesn't work as excepted feel free to report back.

**Pull request closed without merging**
